name: Build LaTeX document
on: [push]
jobs:
    build_latex:
        runs-on: ubuntu-latest
        steps:
          - name: Set up Git repository
            uses: actions/checkout@v4
          - name: Compile latex
            uses: Jatus93/Latex-multicompiler@master
            with:
                path_to_list: main.tex
                artifact: true